# Generated by Django 5.0.1 on 2024-01-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
