# Generated by Django 5.0.1 on 2024-01-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_produit_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.matiere_premiere'),
        ),
    ]
