# Generated by Django 5.0.1 on 2024-01-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_produit_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite',
        ),
        migrations.AddField(
            model_name='produit',
            name='matiere_quantite',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
